name: Release CD

# on:
#   release:
#     types: [published]
on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Provisioning infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: technote-space/get-diff-action@v1
      #   with:
      #     SUFFIX_FILTER: .tf
      - name: Authenticate on GCS
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          project_id: ${{ secrets.PROD_PROJECT_ID }}
          export_default_credentials: true
      - name: Activating GCloud account
        run: |
          env | grep GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        # if: env.GIT_DIFF
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        # if: env.GIT_DIFF
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '-backend-config=conf/prod.tfvars'
        # env:
        #   GOOGLE_APPLICATION_CREDENTIALS: '../client-secret.json'
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        # if: env.GIT_DIFF
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '-var-file=conf/prod.tfvars -out=plan.tfout'
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        # if: env.GIT_DIFF
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: terraform
          tf_actions_comment: true
          args: '"plan.tfout"'
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm test
      - name: Build
        run: npm run build

      - name: Authenticate on GCS
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.PROD_GCP_SA_KEY }}
          project_id: ${{ secrets.PROD_PROJECT_ID }}
      - run: gsutil cp -r dist/spa/* gs://inspector.tykn.tech
        # env:
        #   GOOGLE_APPLICATION_CREDENTIALS: '../client-secret.json'
